import { BROWSER_THEME_COLOR } from "./presentation";

export const renderFatalError = ({
	brand = "Horcrux",
	status = "%sveltekit.status%",
	title = "This page couldn’t load.",
	homeLabel = "Go home",
	homeHref = "/"
} = {}) => `<!doctype html>
<html lang="en" class="dark"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="${BROWSER_THEME_COLOR}"><meta name="robots" content="noindex, nofollow"><title>${status} — Page unavailable — ${brand}</title><style>:root{color-scheme:dark;font-family:-apple-system,BlinkMacSystemFont,"Google Sans Flex",system-ui,"Segoe UI",Roboto,Helvetica,Arial,sans-serif;background:#171717;color:#f7f7f7}*{box-sizing:border-box}body{min-width:320px;min-height:100dvh;margin:0}main{min-height:100dvh;display:grid;grid-template-columns:repeat(12,minmax(0,1fr));gap:32px;align-content:center;padding:max(clamp(24px,6vw,96px),env(safe-area-inset-top)) max(clamp(16px,4vw,72px),env(safe-area-inset-right)) max(clamp(24px,6vw,96px),env(safe-area-inset-bottom)) max(clamp(16px,4vw,72px),env(safe-area-inset-left));overflow-x:hidden}.code{grid-column:1/-1;font-size:clamp(7rem,24vw,21rem);font-weight:600;letter-spacing:-.08em;line-height:.8;font-variant-numeric:tabular-nums}.copy{grid-column:1/-1;z-index:1}h1{max-width:18ch;margin:0;font-size:clamp(2rem,5vw,5rem);font-weight:500;letter-spacing:-.045em;line-height:.95;text-wrap:balance}.actions{display:flex;flex-wrap:wrap;gap:12px;margin-top:32px}.action{min-height:44px;display:inline-flex;align-items:center;justify-content:center;border:0;border-radius:999px;padding:12px 28px;background:#fff;color:#171717;font:600 13px/1 inherit;text-decoration:none;text-transform:uppercase}.secondary{background:#2b2b2b;color:#f7f7f7}:focus:not(:focus-visible){outline:none}:focus-visible{outline:2px solid #a3a3a3;outline-offset:3px}@media(min-width:768px){.code{grid-column:1/span 8}.copy{grid-column:7/-1}}</style></head><body><main><div class="code" aria-hidden="true">${status}</div><section class="copy"><h1>${title}</h1><div class="actions"><a class="action" href="">Reload</a><a class="action secondary" href="${homeHref}">${homeLabel}</a></div></section></main></body></html>`;
