#!/usr/bin/env node
/**
 * Post-build wrapper that adds `queue`, `scheduled`, and the `JobCoordinator`
 * DO class export to the SvelteKit-generated worker.
 *
 * After `vite build` (which runs @sveltejs/adapter-cloudflare):
 *   1. Rename `.svelte-kit/cloudflare/_worker.js` →
 *      `.svelte-kit/cloudflare/_sveltekit-worker.js`.
 *   2. Write a new `_worker.js` that imports the SvelteKit handler + the
 *      pipeline exports from `worker-entry.ts` (compiled by Vite into the
 *      SvelteKit server output).
 *
 * Wrangler picks up the new `_worker.js` via `main` in wrangler.jsonc.
 */

import { existsSync, readFileSync, writeFileSync, renameSync } from "node:fs";
import path from "node:path";
import process from "node:process";

const root = process.cwd();
const generated = path.join(root, ".svelte-kit/cloudflare/_worker.js");
const moved = path.join(root, ".svelte-kit/cloudflare/_sveltekit-worker.js");

if (!existsSync(generated)) {
    console.error(`[wrap-worker] ${generated} not found — did vite build complete?`);
    process.exit(1);
}

// Move the original aside so our wrapper can import from it.
renameSync(generated, moved);

// New entry: pull the SvelteKit handler + pipeline pieces and compose.
const wrapper = `// AUTO-GENERATED by scripts/wrap-worker.mjs — do not edit.
import sveltekit from "./_sveltekit-worker.js";
import { queueConsumer } from "../../src/lib/server/queue/consumer.ts";
import { scheduledSweep } from "../../src/lib/server/cron/sweep.ts";
export { JobCoordinator } from "../../src/lib/server/durable-objects/job-coordinator.ts";

export default {
    fetch: (req, env, ctx) => sveltekit.fetch(req, env, ctx),
    queue: (batch, env, ctx) => queueConsumer(batch, env, ctx),
    scheduled: (controller, env, ctx) => scheduledSweep(controller, env, ctx)
};
`;

writeFileSync(generated, wrapper);
console.log("[wrap-worker] wrote composite _worker.js with queue + scheduled + DO");
